### ISSUE TITLE
SLEEP argument is vulnerable to multiple evaluation

### ISSUE THREAD

**Issue by phoe** [tdrhq/auto-restart#1]
https://github.com/tdrhq/auto-restart/blob/b10bd04e363447326b78ac41703a4e66f3322067/auto-restart.lisp#L33

Solution: use `alexandria:once-only` or equivalent.

**Comment by tdrhq** [comment]
will fix

**Comment by tdrhq** [comment]
Fixed in https://github.com/tdrhq/auto-restart/commit/5004d31c5fe7718087c66708185d92a2fba92c1d

Thanks!

**Comment by tdrhq** [comment]
@phoe Also, since you're really the expert on CL condition system, let me know if I'm somehow reinventing the wheel here :)
