### ISSUE TITLE
(&REST NIL) is not a valid lambda list

### ISSUE THREAD

**Issue by phoe** [tdrhq/auto-restart#2]
https://github.com/tdrhq/auto-restart/blob/b10bd04e363447326b78ac41703a4e66f3322067/auto-restart.lisp#L81

`NIL` is a bad name to be used as a `&REST` variable name, since it names a constant. Try using a gensym maybe? I don't fully follow the logic there.

**Comment by tdrhq** [comment]
This one is correct. So if a rest is provided, say `&rest abc`, then I make the final restart call look something like this:
```
  (apply #'foobar .... abc)
```

If `&rest` is not provided, this logic is just making the apply line look like this:
```
  (apply #'foobar ... nil)
```

The nil is referencing the last argument to apply in this case. For sure it's a little hacky, and doesn't look very readable, but it's correct as far as I can tell (module lots and lots of edge cases)

**Comment by phoe** [comment]
Oooh - OK, understandable. I'd write it like (&REST ()) then, to make it 
a bit clearer that the last NIL is treated as a list rather than the symbol.
